/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_com_zuriquebolos_songsofclassicgames_GMEPlayer */

#ifndef _Included_br_com_zuriquebolos_songsofclassicgames_GMEPlayer
#define _Included_br_com_zuriquebolos_songsofclassicgames_GMEPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_com_zuriquebolos_songsofclassicgames_GMEPlayer
 * Method:    carregarArquivo
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_br_com_zuriquebolos_songsofclassicgames_GMEPlayer_carregarArquivo
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     br_com_zuriquebolos_songsofclassicgames_GMEPlayer
 * Method:    carregarDados
 * Signature: ([BI)Z
 */
JNIEXPORT jboolean JNICALL Java_br_com_zuriquebolos_songsofclassicgames_GMEPlayer_carregarDados
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     br_com_zuriquebolos_songsofclassicgames_GMEPlayer
 * Method:    obterAmostra
 * Signature: (J)[S
 */
JNIEXPORT jshortArray JNICALL Java_br_com_zuriquebolos_songsofclassicgames_GMEPlayer_obterAmostra
  (JNIEnv *, jobject, jlong);

/*
 * Class:     br_com_zuriquebolos_songsofclassicgames_GMEPlayer
 * Method:    terminouMusica
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_br_com_zuriquebolos_songsofclassicgames_GMEPlayer_terminouMusica
  (JNIEnv *, jobject);

/*
 * Class:     br_com_zuriquebolos_songsofclassicgames_GMEPlayer
 * Method:    obterUltimoErro
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_br_com_zuriquebolos_songsofclassicgames_GMEPlayer_obterUltimoErro
  (JNIEnv *, jobject);

/*
 * Class:     br_com_zuriquebolos_songsofclassicgames_GMEPlayer
 * Method:    configurarDiminuicaoVolume
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_br_com_zuriquebolos_songsofclassicgames_GMEPlayer_configurarDiminuicaoVolume
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     br_com_zuriquebolos_songsofclassicgames_GMEPlayer
 * Method:    obterInformacoesMusica
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_br_com_zuriquebolos_songsofclassicgames_GMEPlayer_obterInformacoesMusica
  (JNIEnv *, jobject);

/*
 * Class:     br_com_zuriquebolos_songsofclassicgames_GMEPlayer
 * Method:    liberarRecursos
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_com_zuriquebolos_songsofclassicgames_GMEPlayer_liberarRecursos
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
